from rest_framework import serializers


class TrendingShowSerializer(serializers.Serializer):
    # Common fields for both movies and TV shows
    id = serializers.IntegerField()
    backdrop_path = serializers.CharField(allow_null=True)
    poster_path = serializers.CharField(allow_null=True)
    overview = serializers.CharField()
    media_type = serializers.ChoiceField(choices=['tv', 'movie'])
    adult = serializers.BooleanField()
    original_language = serializers.CharField()
    genre_ids = serializers.ListField(child=serializers.IntegerField())
    popularity = serializers.FloatField()
    vote_average = serializers.FloatField()
    vote_count = serializers.IntegerField()

    # Movie-specific fields
    title = serializers.CharField(required=False)
    original_title = serializers.CharField(required=False)
    release_date = serializers.DateField(required=False)
    video = serializers.BooleanField(required=False)

    # TV show-specific fields
    name = serializers.CharField(required=False)
    original_name = serializers.CharField(required=False)
    first_air_date = serializers.DateField(required=False)
    origin_country = serializers.ListField(child=serializers.CharField(), required=False)

class TrendingShowsResponseSerializer(serializers.Serializer):
    results = TrendingShowSerializer(many=True)
    page = serializers.IntegerField()
    total_pages = serializers.IntegerField()
    total_results = serializers.IntegerField()

class GenreSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()

class MovieDetailSerializer(serializers.Serializer):
    adult = serializers.BooleanField()
    backdrop_path = serializers.CharField(allow_null=True)
    belongs_to_collection = serializers.JSONField(allow_null=True)
    budget = serializers.IntegerField()
    genres = GenreSerializer(many=True)
    homepage = serializers.CharField(allow_null=True)
    id = serializers.IntegerField()
    imdb_id = serializers.CharField()
    original_language = serializers.CharField()
    original_title = serializers.CharField()
    overview = serializers.CharField()
    popularity = serializers.FloatField()
    poster_path = serializers.CharField(allow_null=True)
    production_companies = serializers.ListField(child=serializers.DictField())
    production_countries = serializers.ListField(child=serializers.DictField())
    release_date = serializers.DateField()
    revenue = serializers.IntegerField()
    runtime = serializers.IntegerField()
    spoken_languages = serializers.ListField(child=serializers.DictField())
    status = serializers.CharField()
    tagline = serializers.CharField()
    title = serializers.CharField()
    video = serializers.BooleanField()
    vote_average = serializers.FloatField()
    vote_count = serializers.IntegerField()

class TvDetailSerializer(serializers.Serializer):
    adult = serializers.BooleanField()
    backdrop_path = serializers.CharField(allow_null=True)
    created_by = serializers.ListField(child=serializers.DictField())
    episode_run_time = serializers.ListField(child=serializers.IntegerField())
    first_air_date = serializers.DateField()
    genres = GenreSerializer(many=True)
    homepage = serializers.CharField(allow_null=True)
    id = serializers.IntegerField()
    in_production = serializers.BooleanField()
    languages = serializers.ListField(child=serializers.CharField())
    last_air_date = serializers.DateField()
    last_episode_to_air = serializers.DictField(allow_null=True)
    name = serializers.CharField()
    next_episode_to_air = serializers.DictField(allow_null=True)
    networks = serializers.ListField(child=serializers.DictField())
    number_of_episodes = serializers.IntegerField()
    number_of_seasons = serializers.IntegerField()
    origin_country = serializers.ListField(child=serializers.CharField())
    original_language = serializers.CharField()
    original_name = serializers.CharField()
    overview = serializers.CharField()
    popularity = serializers.FloatField()
    poster_path = serializers.CharField(allow_null=True)
    production_companies = serializers.ListField(child=serializers.DictField())
    production_countries = serializers.ListField(child=serializers.DictField())
    seasons = serializers.ListField(child=serializers.DictField())
    spoken_languages = serializers.ListField(child=serializers.DictField())
    status = serializers.CharField()
    tagline = serializers.CharField()
    type = serializers.CharField()
    vote_average = serializers.FloatField()
    vote_count = serializers.IntegerField()

class TvEpisodeSerializer(serializers.Serializer):
    air_date = serializers.DateField()
    episode_number = serializers.IntegerField()
    id = serializers.IntegerField()
    name = serializers.CharField()
    overview = serializers.CharField()
    production_code = serializers.CharField()
    runtime = serializers.IntegerField()
    season_number = serializers.IntegerField()
    show_id = serializers.IntegerField()
    still_path = serializers.CharField(allow_null=True)
    vote_average = serializers.FloatField()
    vote_count = serializers.IntegerField()
    crew = serializers.ListField(child=serializers.DictField())
    guest_stars = serializers.ListField(child=serializers.DictField())


class TvEpisodesResponseSerializer(serializers.Serializer):
    _id = serializers.CharField()
    air_date = serializers.DateField()
    episodes = TvEpisodeSerializer(many=True)
    name = serializers.CharField()
    overview = serializers.CharField()
    id = serializers.IntegerField()
    poster_path = serializers.CharField(allow_null=True)
    season_number = serializers.IntegerField()
    vote_average = serializers.FloatField()
    
