# Generated by Django 5.1 on 2025-02-27 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowWatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('tv', 'tv'), ('movie', 'movie')], max_length=10)),
                ('tmdb_id', models.IntegerField()),
                ('poster_path', models.CharField(max_length=255)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media_type', 'tmdb_id')},
            },
        ),
        migrations.CreateModel(
            name='MovieProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.IntegerField(default=0)),
                ('total_seconds', models.IntegerField(default=0)),
                ('show_watch_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_progress', to='shows.showwatchprogress')),
            ],
        ),
        migrations.CreateModel(
            name='TvProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.IntegerField(default=0)),
                ('total_seconds', models.IntegerField(default=0)),
                ('season', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=0)),
                ('show_watch_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_progress', to='shows.showwatchprogress')),
            ],
            options={
                'unique_together': {('show_watch_progress', 'season', 'episode')},
            },
        ),
    ]
