# Generated by Django 5.1 on 2025-02-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieprogress',
            unique_together={('show_watch_progress',)},
        ),
    ]
