# Generated by Django 5.1 on 2025-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_movieprogress_total_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showwatchprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
