# Generated by Django 5.1 on 2025-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_movieprogress_created_at_movieprogress_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showwatchprogress',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
