# Generated by Django 5.1 on 2025-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('tv', 'tv'), ('movie', 'movie')], max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster_path', models.CharField(max_length=255)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type', 'season', 'episode')},
            },
        ),
    ]
