# Generated by Django 5.1 on 2025-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_watchurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchurl',
            name='en_subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='watchurl',
            name='es_subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
