# Generated by Django 5.1 on 2025-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_watchurl_en_subtitle_watchurl_es_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchurl',
            name='url',
            field=models.TextField(),
        ),
    ]
